[build]
  command = "npm run build"       
  functions = "netlify/functions"
  publish = "dist"                

[dev]
  functions = "netlify/functions"
  command = "npm run dev"         

# Optional: environment variables (bisa juga diset via Netlify UI)
[build.environment]
  NODE_ENV = "production"
  MONGODB_URI = "mongodb://localhost:27017/mlaku"
  JWT_SECRET = "mlakulaku-sangat-rahasia"

# Optional: redirect rules jika perlu (misal API route /functions/*)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
